### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by juliacbauer** [RenaBMew/com6338-10-10-bauer-brown-colver#1]
Issue for creating home page

**Comment by juliacbauer** [comment]
- [x] CSS styling
- [x] Nav bar
- [x] Basic body text describing site
- [x] Click event buttons to other pages
- [x] Movie quote generator
- [x] Footer

**Comment by RenaBMew** [comment]
Created a movie quote generator instead of the hangman game =)

Feel free to add any of your favorite quotes!

**Comment by RenaBMew** [comment]
Adding some APIs for reference, if needed:
IMDB APIs
https://www.omdbapi.com/#usage
https://github.com/SpEcHiDe/IMDbOT
https://developer.themoviedb.org/reference/intro/getting-started

Streaming APIs
https://api.watchmode.com/

Trailer API
https://www.traileraddict.com/trailerapi
